version: "3.9"

services:
  front:
    build:
      context: ./apps/front/app
    command: ["npm", "run", "start"]
    volumes:
      - ./apps/front/app:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - back
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - HOST=0.0.0.0

  back:
    build: ./apps/back
    volumes:
      - ./apps/back:/app
      - /app/node_modules
    ports:
      - "5000:3000"
    environment:
      - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - JWT_SECRET=s3cret
    depends_on:
      - db
  
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata: