# Dockerfile.prod
FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --omit=dev && npm cache clean --force

COPY . .

RUN npm run build

RUN apk add --no-cache postgresql-client

RUN chmod +x entrypoint.sh

ENV NODE_ENV=production

EXPOSE 3000

ENTRYPOINT ["./entrypoint.sh"]
CMD ["npm", "run", "start"]
