name: Weekly Event Cleanup

# Auto run all monday at 2AM
on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch: # Permit manual exec

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          # TODO Add secrets in GitHub
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22:alpine

      - name: Run cleanup script
        # TODO Update user and server
        run: ssh user@your-server 'cd /path/to/project && npm ci && node dist/database/cleanup.js'
        env:
          PG_URL: postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@${{ secrets.POSTGRES_HOST }}:5432/${{ secrets.POSTGRES_DB }}
